name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Patchy solution to different build contexts
        run: |
          zip privateVoterFront.zip -r webapp/privateVoterFront
          cp webapp/requirements.txt .
          mkdir docker
          cp webapp/docker/entrypoint.sh docker/
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS }}
          repository: vojtatuma/private-voter
          tag_with_ref: true
          file: webapp/docker/Dockerfile
