name: run-pytest
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v2
       with:
         python-version: 3.7
     - run: |
         apt-get update
         apt-get upgrade sqlite3
         python -m pip install --upgrade pip
         pip install -r webapp/requirements.txt
         pip install pytest==6.2.1 flake8==3.8.4
     - run: |
         flake8 webapp/ --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 webapp/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=E302,E251,E226,E261,W504
     - run: pytest webapp/

